<h1>Категории</h1>

<table class="table table-striped table-hover ">
    <tbody>
        <tr>
            <th>#</th>
            <th>Ключ</th>
            <th>Название</th>
            <th>Действие</th>
        </tr>
        <?php
        foreach ($categories as $item) {
            echo "<tr>
                    <td>{$item->getId()}</td>
                    <td>{$item->getCategoryKey()}</td>
                    <td>{$item->getCategoryName()}</td>";
            echo '<td><a href="' . $this->url('admin/category', array('action' => 'edit', 'id' => $item->getId())) . '">Редактировать</a>&nbsp;&nbsp;
                      <a href="' . $this->url('admin/category', array('action' => 'delete', 'id' => $item->getId())) . '" onclick="if (confirm(\'Удалить запись?\')) { document.location = this.href; } return false;">Удалить</a></td>';
        }
        ?>
    </tbody>
</table>